allow_remote_control yes
listen_on unix:${XDG_RUNTIME_DIR}/kitty

font_family MonoLisa Variable
font_size 14.0

symbol_map U+276E-U+276F DejaVu Sans

background #002b36
foreground #839496
cursor     #00a600
cursor_text_color background
cursor_shape block
cursor_shape_unfocused hollow
cursor_blink_interval 1.0
shell_integration enabled no-cursor

selection_foreground #ffffff
selection_background #000000

enable_audio_bell yes
audio_bell_path /usr/share/sounds/Yaru/stereo/bell.ogg

copy_on_select clipboard
mouse_map middle release ungrabbed paste_from_clipboard

hide_window_decorations titlebar-only

tab_bar_style separator
tab_separator ""
tab_title_template " {title} "
active_tab_foreground   #000000
active_tab_background   #00aa00
inactive_tab_foreground #000000
inactive_tab_background #003500
inactive_tab_font_style normal

remember_window_size no
initial_window_width 70c
initial_window_height 18c

color0  #171421
color1  #c01c28
color2  #26a269
color3  #a2734c
color4  #1658a9
color5  #a347ba
color6  #2aa1b3
color7  #d0cfcc
color8  #5e5c64
color9  #f66151
color10 #33d17a
color11 #e9ad0c
color12 #1975e5
color13 #c061cb
color14 #33c7de
color15 #ffffff

map ctrl+shift+enter new_window_with_cwd
map ctrl+shift+t new_tab_with_cwd

enabled_layouts splits,stack
map ctrl+shift+r layout_action rotate

scrollbar_visibility overlay
scrollback_lines 10000

selection_foreground none

map ctrl+shift+o kitten hints --type=url

include tab.conf
